### ISSUE TITLE
Could you help us do t3d too? We got the vertex info printing. GPL project. Did wolfenstine:enemy territory bsp last year, some obj exports from minetest and bzflag this year

### ISSUE THREAD

**Issue by chaosesqueteam** [iainmckay/unrealengine4-t3d#1]
Could you help us do t3d too? We got the vertex info printing. GPL project. Did wolfenstine:enemy territory bsp last year, some obj exports from minetest and bzflag this year.
Trying t3d but got burnt out.
Used to map for unreal stuff and ut99.
Bro.
https://github.com/chaosesqueteam/t3d_attempt_darkplaces_workingon/

**Comment by chaosesqueteam** [comment]
Here's our full project: sourceforge.net/projects/chaosesqueanthology/
Screenshots: https://chaosesqueteam.itch.io/chaosesque-anthology
, all opensource, media etc too

We have city generation and stuff, with interiors to the buildings, and we've done 100s of models for the game, all opensource. You can procedurally generate a map too using the spawnarray, spawnradial, etc routines we added. 
	We want more map/model support and then realized we can't do it alone and should be like a normal opensource and freesoftware project and ask for help. We did a few formats ourself but ... got burnt out abit.
	We used to map in unreal back in the day, and were wondering if t3d support could be added? We broke the ice and got the vertex info printing, (the file recognized and can be told to be a map by the command (map somefile.t3d), in model_brush.c (last function), but that's as far as we got.

Could you help?
We also gathered up resources regarding t3d here (https://sourceforge.net/p/chaosesqueanthology/discussion/general/thread/72c4ff80c1/ ) (though people from devrant are spamming it with garbage or offtopic rants, but the files are there)

**Comment by iainmckay** [comment]
Sorry, I'm not really sure what you want here. If there are bugs in this
library I can certainly help fix them.

**Comment by chaosesqueteam** [comment]
Well in our Quake1 fork we implemented various additions to make various map formats work
Last year: Wolfenstine:Enemy Territory BSP. (took a month)
This summer: Minetest obj export and bzflag obj export. (took less time, wasn't as hard)

We'd like to add t3d support but don't get it and are burnt out;
So we realized that most opensource projects have more than one person working on them.

We used to map for unreal and unreal tournament and have original works in the parent formats.
We tried ourselves to load t3d format into the engine and edited model_brush.c; and got to the point
where we recognized and printed the vertex info to the console.
But we knew we were in too deep.

2 years ago we also extended the max entities in the engine from 32k to 4 million by editing the internals
and the netcode, adding a new net protocol one could choose, and a backwards compatable way aswell
That can be used with out procedural map making QC code (spawnarrays, spawnradials, etc) to make cities etc.

So we've been doing all these additions.
Also we modeled and coded many GPL weapons that are similar to the unr ones.
And our project has over 200 weapons, all opensource.
So... the idea is that we haven't done nothing: we've done all we could with our present ability.
And with the wolfenstine:enemy territory feature we programmed we gained access to 600 maps for all this.
And with the extra obj work : anything that can be loaded into blender can be made into a map (obj_from_mc)
(or exported from minetest etc) (the engine could already support: Q3 and HL maps, and iqm etc models)

So we want .t3d too. Because then one could export from unrealed too.
They could use radiant (now), blender (now), and if t3d, could use unrealed too.

We've done a decade of work on our fork. Media, gamecode, weapons, songs, sound, maps, engine code.
We want to bridge quake and unreal.

Could you help? The obj code does it all in one function in model_brush.c, and then does "shadowbsp", 
I think to make a bsp tree automatically so the programmer doesn't have to bother with that. We started
to edit it in the last function in the file, to adapt it to t3d; and then researched t3d and gathered various projects
that work on t3d (in a post). But we know we're in too deep.






On Monday, September 11, 2023 at 01:44:29 PM EDT, Iain Mckay ***@***.***> wrote: 






Sorry, I'm not really sure what you want here. If there are bugs in this 
library I can certainly help fix them.

**Comment by iainmckay** [comment]
I'm sorry but I've not worked in a quake engine in over a decade and I don't have the time to dedicate to such a project.
